name: sundaymart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.10.30+51

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  upgrader: ^11.3.1
  intl: ^0.20.0
  lottie: ^3.3.1
  get_it: ^8.0.3
  shimmer: ^3.0.0
  location: ^8.0.0
  auto_route: ^5.0.4
  share_plus: ^11.0.0
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  url_launcher: ^6.1.7
  flutter_remix: ^0.0.3
  osm_nominatim: ^3.0.1
  google_fonts:
  google_sign_in: ^6.3.0
  flutter_riverpod: ^2.1.3
  connectivity_plus: ^6.1.0
  freezed_annotation: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.0.15
#  flutter_barcode_scanner: ^2.0.0
#  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.3.1
#  flutter_native_splash: ^2.2.16
#  flutter_login_facebook: ^2.0.1
  # flutter_calendar_carousel: ^2.5.3
  encrypt: ^5.0.3
  flutter_bloc: ^9.1.1
  conditional_builder_null_safety: ^0.0.6
  marquee: ^2.2.3
  fluttertoast: ^8.2.1
#  share: ^2.0.4
  skeletonizer: ^1.4.2
  carousel_slider: ^5.0.0
#  my_fatoorah: ^3.2.0
  awesome_notifications: ^0.10.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.8.0
#  mobile_scanner: ^6.0.10
  myfatoorah_flutter: ^3.1.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_dynamic_links: ^6.0.10
  flutter_tawkto: ^0.0.5
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  flutter_google_places_sdk: ^0.4.0
  percent_indicator: ^4.2.2
  tabby_flutter_inapp_sdk: ^1.9.0
  uuid: ^4.5.0
  google_maps_places_autocomplete_widgets: ^1.3.3
  #apple payment
  in_app_purchase_storekit: ^0.3.21
  in_app_purchase: ^3.2.1
  qr_code_scanner_plus: ^2.0.10+1
  flutter_native_splash: ^2.4.4
  pretty_dio_logger: ^1.4.0
  uni_pay: ^3.0.3
  easy_localization: ^3.0.7+1
  pay: ^3.2.1
  # apple_pay_flutter: ^1.0.3
#  webview_flutter: ^3.0.4
#  tamara_flutter_sdk: ^1.0.14

#dependency_overrides:
#  flutter_inappwebview: ^6.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.14.3
  win32: ^5.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/all/
    - assets/images/dark_mode/
    - assets/images/light_mode/
    - shorebird.yaml

  fonts:
    - family: Monadi
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: ArabicTwo_Bold
      fonts:
        - asset: assets/fonts/ArabicTwo_Bold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/light_mode/logo.png"
  adaptive_icon_background: "assets/images/dark_mode/logo.png"
  adaptive_icon_foreground: "assets/images/light_mode/logo.png"
  ios_dark_image_path: "assets/images/dark_mode/logo.png"
#  image_path: 'assets/images/all/splash_tomouna.png'

flutter_native_splash:
  android_12:
  fullscreen: true
  background_image: 'assets/images/all/splash_tomouna.png'
