// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF_cEoi7D1ZS48VAkhKc1NFnbqtvGgpU8',
    appId: '1:323136603330:web:05857c2748ea0bc128275b',
    messagingSenderId: '323136603330',
    projectId: 'tamwinat-dbfdd',
    authDomain: 'tamwinat-dbfdd.firebaseapp.com',
    storageBucket: 'tamwinat-dbfdd.firebasestorage.app',
    measurementId: 'G-BSX3WDWY9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1MSG9t9E22r-LIR6cZquAMXLV4HAgX0',
    appId: '1:323136603330:android:c012e246dc8cd82828275b',
    messagingSenderId: '323136603330',
    projectId: 'tamwinat-dbfdd',
    storageBucket: 'tamwinat-dbfdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVi1lU4UKTbdFmXZNUV6LAWFfG-SeJDao',
    appId: '1:323136603330:ios:4a8c911d3d8e86f128275b',
    messagingSenderId: '323136603330',
    projectId: 'tamwinat-dbfdd',
    storageBucket: 'tamwinat-dbfdd.firebasestorage.app',
    iosBundleId: 'com.apptamwe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVi1lU4UKTbdFmXZNUV6LAWFfG-SeJDao',
    appId: '1:323136603330:ios:f069b0ae74d3adaf28275b',
    messagingSenderId: '323136603330',
    projectId: 'tamwinat-dbfdd',
    storageBucket: 'tamwinat-dbfdd.firebasestorage.app',
    iosBundleId: 'com.example.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF_cEoi7D1ZS48VAkhKc1NFnbqtvGgpU8',
    appId: '1:323136603330:web:26bb007ec00ad62328275b',
    messagingSenderId: '323136603330',
    projectId: 'tamwinat-dbfdd',
    authDomain: 'tamwinat-dbfdd.firebaseapp.com',
    storageBucket: 'tamwinat-dbfdd.firebasestorage.app',
    measurementId: 'G-697V7T9PYH',
  );

}