// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBps8T2QQZ3M6BloZ71sIiFpWKyTHy3ArU',
    appId: '1:208221222611:web:948a5b1d06607736ef4626',
    messagingSenderId: '208221222611',
    projectId: 'onesysteamapp',
    authDomain: 'onesysteamapp.firebaseapp.com',
    storageBucket: 'onesysteamapp.appspot.com',
    measurementId: 'G-KTV8ZTQET0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmn-akpAgdwRTvald49d9iEWu82FQcn4',
    appId: '1:208221222611:android:fba70f293c462a6bef4626',
    messagingSenderId: '208221222611',
    projectId: 'onesysteamapp',
    storageBucket: 'onesysteamapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAH-9l2JUoemnr6pyWkj_tb1VFQC3b2Q',
    appId: '1:208221222611:ios:eb63b799b64328dfef4626',
    messagingSenderId: '208221222611',
    projectId: 'onesysteamapp',
    storageBucket: 'onesysteamapp.appspot.com',
    androidClientId: '208221222611-so9585p22c8sst98299alqjtk1fvnljj.apps.googleusercontent.com',
    iosClientId: '208221222611-k9e4dkaaeabqr4g1imomfuibnv9ralvp.apps.googleusercontent.com',
    iosBundleId: 'com.apptamwe.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAH-9l2JUoemnr6pyWkj_tb1VFQC3b2Q',
    appId: '1:208221222611:ios:bc95d8f53e663f86ef4626',
    messagingSenderId: '208221222611',
    projectId: 'onesysteamapp',
    storageBucket: 'onesysteamapp.appspot.com',
    androidClientId: '208221222611-so9585p22c8sst98299alqjtk1fvnljj.apps.googleusercontent.com',
    iosClientId: '208221222611-l22cuqjsuqe1ka0tpjegfc0rbklm786f.apps.googleusercontent.com',
    iosBundleId: 'net.sundaymart.sundaymart',
  );
}
